""" NAME:BHARGAVI
DATE: 17-MAY-2022
DAY: TUESDAY
TIME: 2:00PM
 FILE DESC: END-SEPERATE-COMBINATION
 """

#  SEPERATE CAN ONLY BE DONE USING
# print(1,2,3,4,5,sep='-')
# print('python','3.10.4',sep='-')

# end
# print('hi\n'*3,end='')
# print('hi'*4)
# print('my name is',end=' ')
# print('bhargavi')

#combination of end and seperate
# print(1,2,3,4,5,sep='-',end='.')
# print(6,8,0)